<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [1]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [4]:
array1 = np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [5]:
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [18]:
array3 = [0,2,0,3,0,4,0]
np.where(array3)

(array([1, 3, 5], dtype=int64),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [23]:
array4 = np.random.rand(3,3)
array4

array([[0.5394045 , 0.27097007, 0.47288207],
       [0.77796548, 0.40616144, 0.70336822],
       [0.15645694, 0.71459638, 0.23098423]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [28]:
array5 = np.random.rand(10)*100
print(f"Max {np.max(array5)}. Min: {np.min(array5)}")

Max 96.95544347091949. Min: 1.2020441047285835


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [39]:
array6 = np.random.rand(10)
display(array6)
display(array6[::-1])

array([0.71419654, 0.59783423, 0.70174559, 0.11934445, 0.71939116,
       0.97987527, 0.53294993, 0.12635007, 0.20708002, 0.5442691 ])

array([0.5442691 , 0.20708002, 0.12635007, 0.53294993, 0.97987527,
       0.71939116, 0.11934445, 0.70174559, 0.59783423, 0.71419654])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [50]:
array6 = np.random.randint(1,24,(2,3,4))
array6

array([[[ 3, 19, 13,  6],
        [ 9, 18, 23,  8],
        [13,  4, 17,  2]],

       [[19, 16, 13, 15],
        [16,  6,  1, 10],
        [ 2,  3,  5,  6]]])

Seleccionar el primer 15

In [51]:
array6[array6 == 15][0]

15

Selecciona todos los elementos del primer array

In [53]:
array6[0,:,:]

array([[ 3, 19, 13,  6],
       [ 9, 18, 23,  8],
       [13,  4, 17,  2]])

Selecciona la última fila del último array

In [61]:
array6[-1,-1,:]

array([2, 3, 5, 6])


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [56]:
array7 = np.random.randint(1,30,(2,3,5))
array7

array([[[21,  3, 26, 28, 22],
        [20, 12, 22, 28, 13],
        [28,  4,  7,  2, 29]],

       [[18, 13, 21,  7,  2],
        [ 9, 21, 24,  4, 13],
        [27, 17, 18, 18,  4]]])


- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.


In [62]:
array7[0,:,:2]

array([[21,  3],
       [20, 12],
       [28,  4]])


- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.

In [63]:
array7[-2:,:,:]

array([[[21,  3, 26, 28, 22],
        [20, 12, 22, 28, 13],
        [28,  4,  7,  2, 29]],

       [[18, 13, 21,  7,  2],
        [ 9, 21, 24,  4, 13],
        [27, 17, 18, 18,  4]]])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [66]:
array8 = np.random.randint(1,24,(4,3,2))
array8

array([[[15,  1],
        [16, 12],
        [13,  1]],

       [[ 3,  5],
        [ 5,  3],
        [10,  9]],

       [[14, 10],
        [18, 16],
        [ 7, 19]],

       [[22,  3],
        [11, 23],
        [14,  2]]])

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

In [67]:
array8[1,1,:] = 8
array8

array([[[15,  1],
        [16, 12],
        [13,  1]],

       [[ 3,  5],
        [ 8,  8],
        [10,  9]],

       [[14, 10],
        [18, 16],
        [ 7, 19]],

       [[22,  3],
        [11, 23],
        [14,  2]]])


- Cambia todos los valores del último array a `-1`.

In [68]:
array8[-1,:,:] = -1
array8

array([[[15,  1],
        [16, 12],
        [13,  1]],

       [[ 3,  5],
        [ 8,  8],
        [10,  9]],

       [[14, 10],
        [18, 16],
        [ 7, 19]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [69]:
array9 = np.random.randint(-10,13,(2,4,3))
array9

array([[[ -8,   5,   0],
        [  4,  -6,  -3],
        [  0, -10,   2],
        [  1,   4,  -9]],

       [[  6,  -8,   4],
        [  4,  -8,  -5],
        [  3,  10,  -9],
        [  1,  -1,  10]]])

- Selecciona todos los elementos mayores a `5`.

In [70]:
array9[array9 > 5]

array([ 6, 10, 10])


- Reemplaza todos los elementos negativos por `0`.


In [71]:
array9[array9 < 0] = 0
array9

array([[[ 0,  5,  0],
        [ 4,  0,  0],
        [ 0,  0,  2],
        [ 1,  4,  0]],

       [[ 6,  0,  4],
        [ 4,  0,  0],
        [ 3, 10,  0],
        [ 1,  0, 10]]])

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [73]:
array10 = np.random.randint(1,27,(3,3,3))
array10

array([[[ 3, 17,  6],
        [ 2,  9, 15],
        [ 8, 21, 23]],

       [[ 8, 16, 23],
        [23, 19, 14],
        [ 7,  5, 16]],

       [[13, 13,  3],
        [22,  8,  8],
        [ 2,  4, 11]]])

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

In [74]:
array10[1,:,:2]

array([[ 8, 16],
       [23, 19],
       [ 7,  5]])

- Selecciona todos los elementos del tercer array que sean mayores que `20`.

In [79]:
array10[2,:,:][array10[2,:,:]>20]

array([22])

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [81]:
array11 = np.random.randn(10)*100
array11

array([ -42.03132402,    8.5629941 ,   10.5378418 , -108.57161915,
        242.0411363 ,   45.60730316,   42.25741014,   18.01939254,
         82.09688247,  -96.85289688])

In [82]:
array11[array11 == np.max(array11)] = 0
array11[array11 == np.min(array11)] = 0
array11

array([-42.03132402,   8.5629941 ,  10.5378418 ,   0.        ,
         0.        ,  45.60730316,  42.25741014,  18.01939254,
        82.09688247, -96.85289688])

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [86]:
array12 = np.random.randint(1,100,(15))
np.sort(array12)[::-1]

array([93, 86, 79, 74, 74, 73, 69, 67, 66, 57, 56, 24, 24, 22, 13])

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [87]:
array11 = np.random.randint(1,100,(4,4))
np.sum(array11)

746

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [89]:
array12 = np.ones((5,5))
array12[1:4,1:4]=0
array12

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [127]:
array13 = np.random.randn(1000)*50
array13

array([ 4.27970696e+01, -2.82224008e+01, -1.57561695e+00, -8.52197384e+00,
        4.20201537e+01, -2.65575445e+01, -2.39068660e+01,  1.82448563e+01,
       -1.76533008e+01,  4.10468542e+01,  7.71289109e+01,  7.79705608e+01,
        3.83785918e+01,  7.87063072e+01,  3.12487667e+01, -2.47355342e+01,
       -3.82395827e+01,  9.02251994e+00,  6.75532670e+01,  9.67347227e+01,
       -4.54040748e+01,  1.76401077e+01,  9.30419892e+01, -5.35309333e+01,
       -2.43981894e+01,  7.26430311e+01,  4.61951782e+01,  2.89789203e+01,
        4.81946048e+01,  3.50134101e+01, -6.22235747e+01, -2.47832313e+01,
        3.61219783e+01, -1.87896490e+01, -2.00439312e+01, -3.23523287e+01,
       -4.66240667e+01,  2.56258328e+01, -6.95421998e+01,  2.74799385e+01,
        3.34281510e+01,  1.60274763e+01, -1.29620216e+01, -4.14790576e+00,
       -9.46337796e+00,  3.09233044e+00,  2.53938138e+01, -9.13036337e+00,
       -2.47471414e+01,  4.32534950e+01,  6.98638602e+01, -7.76323835e+00,
       -4.88615503e+01,  

In [128]:
display(np.mean(array13))
np.std(array13)

-0.05294669059515559

49.499331741131165

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).


In [103]:
array14 = np.random.randint(1,24,(2,3,4))
array14

array([[[11,  5,  5, 20],
        [20, 14, 10,  6],
        [21, 12, 14, 12]],

       [[ 3, 15, 10,  8],
        [17, 10, 20, 17],
        [23,  5, 22, 19]]])

In [106]:
np.transpose(array14)

array([[[11,  3],
        [20, 17],
        [21, 23]],

       [[ 5, 15],
        [14, 10],
        [12,  5]],

       [[ 5, 10],
        [10, 20],
        [14, 22]],

       [[20,  8],
        [ 6, 17],
        [12, 19]]])


- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


Transponiendo el array e invirtiendo el orden de sus ejes, las matrices pasan de 2 a 4, las filas siendo el punto de pivote quedan igual y las columnas pasan de 2 a 4.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [109]:
array15 = np.random.randint(1,24,(3,4,2))
array15

array([[[ 9, 19],
        [12, 14],
        [15,  7],
        [ 2,  7]],

       [[ 4, 16],
        [20,  1],
        [23,  3],
        [14, 14]],

       [[ 4,  7],
        [15, 11],
        [ 6,  8],
        [11, 17]]])

In [110]:
np.transpose(array15,(1,0,2))

array([[[ 9, 19],
        [ 4, 16],
        [ 4,  7]],

       [[12, 14],
        [20,  1],
        [15, 11]],

       [[15,  7],
        [23,  3],
        [ 6,  8]],

       [[ 2,  7],
        [14, 14],
        [11, 17]]])

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [113]:
array16 = np.random.randint(1,24,(3,2,4))
array16

array([[[ 7, 13, 18,  2],
        [18,  4, 18, 14]],

       [[21, 20, 23,  9],
        [14, 17,  3,  4]],

       [[18, 14,  7, 22],
        [ 1, 19,  5,  3]]])

In [114]:
np.transpose(array16,(2,0,1))

array([[[ 7, 18],
        [21, 14],
        [18,  1]],

       [[13,  4],
        [20, 17],
        [14, 19]],

       [[18, 18],
        [23,  3],
        [ 7,  5]],

       [[ 2, 14],
        [ 9,  4],
        [22,  3]]])

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [134]:
array17 = np.random.randint(-10,10,(3,4,5))
array17

array([[[  5,   2,   5,   6,  -3],
        [ -5,   6,  -3,   0,   2],
        [ -4,   4,  -3,  -5,   9],
        [  0,   9,  -4,  -5,  -4]],

       [[-10,   3,  -5,  -9, -10],
        [  3,  -4,   0,   4, -10],
        [  2,  -3,   0,   1,   2],
        [  7,   5, -10,   0, -10]],

       [[ -5,  -1,   9,  -9,   6],
        [  6,  -2,  -5,   1,  -8],
        [ -7,  -2,  -9,  -8,   7],
        [ -1,   9,   6,   8,   3]]])

In [135]:
array17_empty = np.zeros((3,4,5),str)
array17_empty

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [137]:
array17_empty[array17 == np.median(array17)] = "M"
array17_empty[array17 > np.median(array17)] = "X"
array17_empty[array17 < np.median(array17)] = "Y"
array17_empty[array17 == np.max(array17)] = "MAX"
array17_empty[array17 == np.min(array17)] = "MIN"

In [138]:
array17_empty

array([[['X', 'X', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', 'M', 'X'],
        ['Y', 'X', 'Y', 'Y', 'M'],
        ['M', 'M', 'Y', 'Y', 'Y']],

       [['M', 'X', 'Y', 'Y', 'M'],
        ['X', 'Y', 'M', 'X', 'M'],
        ['X', 'Y', 'M', 'X', 'X'],
        ['X', 'X', 'M', 'M', 'M']],

       [['Y', 'Y', 'M', 'Y', 'X'],
        ['X', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'X'],
        ['Y', 'M', 'X', 'X', 'X']]], dtype='<U1')

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [147]:
array18 = np.array([[1,0,0,0],[1,0,0,0],[1,1,1,1],[1,0,0,0]])
array18

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])

In [154]:
lista_iguales = []
for n_fila, fila in enumerate(array18):
    for n_columna, columna in enumerate(np.transpose(array18)):
        if all(columna == fila):
            lista_iguales.append([n_fila,n_columna])

lista_iguales

[[2, 0]]